### ISSUE TITLE
Links on footer redirect back to same page

### ISSUE THREAD

**Issue by aravindvnair99** [dsccodecollab/dsccodecollab.github.io#15]
The Social Media icons, `Useful Links` and `Other Resources` all navigate to `https://codeculture.netlify.app`.

![image](https://user-images.githubusercontent.com/22199259/99406529-febf4f00-2913-11eb-96ac-a32b10171d69.png)

**Comment by abhinavsri360** [comment]
This can help: https://linktr.ee/thecodingculture

**Comment by aravindvnair99** [comment]
Social media links have been fixed. `Useful links` and `Other resources` need to be fixed.

**Comment by abhinavsri360** [comment]
We need to generate links for that :/ will provide resources soon

**Comment by call-me-bk** [comment]
`Community partners` and `sponsors` have been fixed. `Provacy policy` and `Terms and conditions` still redirect back to the home page.

**Comment by shawavisek35** [comment]
> `Community partners` and `sponsors` have been fixed. `Provacy policy` and `Terms and conditions` still redirect back to the home page.

Yes because we don't have any privacy policy and terms of condition yet. 😅

**Comment by soyo-kaze** [comment]
why not add a 404 page or page under maintenance 🤔

**Comment by soyo-kaze** [comment]
> 
> 
> why not add a 404 page or page under maintenance 🤔
> (**_leme try it_**)

**late but here I am:** Created a 404 page (will push code as soon as I get access)

**Comment by abhinavsri360** [comment]
You already have access don't you?

**Comment by aravindvnair99** [comment]
> You already have access don't you?

@abhinavsri360 Even I don't have access.

**Comment by soyo-kaze** [comment]
> 
> 
> You already have access don't you?

but can't push changes

**Comment by abhinavsri360** [comment]
How come, you guys are already members of the org and org members do have write access, I modified the access terms rn, are you able to make changes now!?

**Comment by soyo-kaze** [comment]
yo!! it worked (please do have a look on what i did. Branch: sameer-404-page) m having a problem, explained that on discord web dev section

**Comment by soyo-kaze** [comment]
@aravindvnair99 Check #35 and close this issue if this fixed it.

**Comment by aravindvnair99** [comment]
> @aravindvnair99 Check #35 and close this issue if this fixed it.

@soyo-kaze I've left a review on the PR thread: https://github.com/dsccodecollab/dsccodecollab.github.io/pull/35#pullrequestreview-591048644
